### ISSUE TITLE
question about keyframe selection method

### ISSUE THREAD

**Issue by TheCuriousJoe** [edexheim/info_ext_calib#1]
Hi eric, excellent work for info_ext_calib!

I have tried your code on EuRoC dataset. It seems that the entropy-based keyframe selection method doesn't work well. Could you give me some advice or suggestion about how to get good performance on EuRoC dataset or my own autodrive dataset like KITTI?

There is a lot of "# todo" in your code. Do you have any plan to update your code recently?

Look forward to your reply!

**Comment by edexheim** [comment]
Which EuRoC sequences did you specifically try?

The Vicon room sequences (other than the Hard ones) should work, but I can look into this if not.  One likely reason for challenges would be the feature tracking, as I used a standard KLT implementation and this was not a major focus.  In the Hard sequences for example, the feature tracking will not perform well with the default parameters due to the challenging brightness conditions.

**Comment by TheCuriousJoe** [comment]
When i use default params on V1_01_easy and run "./calibrate euroc /euroc/V1_01_easy/mav0/", the program stops running for a while, and the output of the program is as follows.

![image](https://user-images.githubusercontent.com/28175538/197439355-7e1589ad-9ef1-494e-958e-91f6b5acea9d.png)

**Comment by edexheim** [comment]
I just ran it and had no crash, so I am wondering if there is a version difference.  After the threads are started, there should be some print outs indicating that segments are proposed.

The symbol "p0" must be from the triangulation module, which I modified from the original GTSAM code.  I added in some checks to see if the triangulation was under-constrained, and there is a catch to avoid a crash.  What version of GTSAM and Boost are you using?

**Comment by TheCuriousJoe** [comment]
My Boost version is 1.71.0, GTSAM version is 4.2.0, OpenCV version is 4.5.5, Pangolin Version is 0.8.
Here is my Cmake file.
![image](https://user-images.githubusercontent.com/28175538/197666195-afa7e2ea-6de3-4c7c-90bc-e1141f0318b5.png)
Here is my cmake output.
![image](https://user-images.githubusercontent.com/28175538/197666607-dbd83f73-2b8c-4de1-a8e1-065bc96c543c.png)

**Comment by TheCuriousJoe** [comment]
In line 144 of "calibrate.cpp", i uncommented code below
`std::cout << frame_id << " " << data_reader->getTimestamp(frame_id) << " " << data_reader->getTimestamp(frame_id+1) <<  std::endl`
and got the following output.
![image](https://user-images.githubusercontent.com/28175538/197670292-a435f98c-14f7-4d39-9162-875a011cb5e4.png)

**Comment by edexheim** [comment]
I apologize for the delay.  I will try a fresh install of dependencies on an Ubuntu system this week, as I am wondering if the exception is defined differently on other systems/versions.  I originally developed on MacOS and an older version of GTSAM.  Are you using Ubuntu currently?

**Comment by edexheim** [comment]
Hello,
I have fixed the exception catch in 88b5b43cac32b2dc3477e719386cc6b86b6d3a6e, and it now works on my Ubuntu machine.  Let me know if this fixes the issue for you.

**Comment by TheCuriousJoe** [comment]
Hi, i have changed the exception catch follow by https://github.com/edexheim/info_ext_calib/commit/88b5b43cac32b2dc3477e719386cc6b86b6d3a6e, and it works! 
Thanks! Great work again!
